-- MySQL Script generated by MySQL Workbench
-- Mon Feb 10 14:37:27 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bilregister
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bilregister
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bilregister` DEFAULT CHARACTER SET utf8mb4 ;
USE `bilregister` ;

-- -----------------------------------------------------
-- Table `bilregister`.`eiere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bilregister`.`eiere` (
  `Fnr` INT(11) NOT NULL AUTO_INCREMENT,
  `fornavn` VARCHAR(20) NOT NULL,
  `etternavn` VARCHAR(20) NOT NULL,
  `adresse` VARCHAR(50) NOT NULL,
  `postnr` INT(4) NOT NULL,
  `epost` VARCHAR(30) NOT NULL,
  `tlf` VARCHAR(8) NOT NULL,
  `tid` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`Fnr`))
ENGINE = InnoDB
AUTO_INCREMENT = 809671251
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bilregister`.`biler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bilregister`.`biler` (
  `RegNr` VARCHAR(8) NOT NULL,
  `Type` VARCHAR(20) NOT NULL,
  `Merke` VARCHAR(20) NOT NULL,
  `Farge` VARCHAR(20) NOT NULL,
  `Fnr` INT(11) NOT NULL,
  PRIMARY KEY (`RegNr`),
  INDEX `brukere-eiere` (`Fnr` ASC),
  CONSTRAINT `brukere-eiere`
    FOREIGN KEY (`Fnr`)
    REFERENCES `bilregister`.`eiere` (`Fnr`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bilregister`.`brukere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bilregister`.`brukere` (
  `brukernavn` VARCHAR(20) NOT NULL,
  `passord` VARCHAR(20) NOT NULL,
  `navn` VARCHAR(50) NOT NULL,
  `organiasjon` VARCHAR(50) NOT NULL,
  `rettighet` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`brukernavn`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bilregister`.`logg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bilregister`.`logg` (
  `id` INT(6) NOT NULL AUTO_INCREMENT,
  `tid` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `brukernavn` VARCHAR(50) NOT NULL,
  `beskrivelse` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 47
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bilregister`.`norske_postnummer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bilregister`.`norske_postnummer` (
  `postnummer` VARCHAR(10) NULL DEFAULT NULL,
  `poststed` VARCHAR(20) NULL DEFAULT NULL,
  `kommunenummer` VARCHAR(13) NULL DEFAULT NULL,
  `kommunenavn` VARCHAR(27) NULL DEFAULT NULL,
  `kategori` VARCHAR(8) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
